/-  Let I ⊂ k[x1, . . . , xn] be an ideal that can be generated by r elements.
Show that every irreducible component of V (I) has dimension ≥ n − r.
-/

import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.RingTheory.Algebraic

namespace Mv_Polynomial

variable {k : Type*} [CommSemiring k] {σ :Type*} {s: σ → ℕ} {a: k} {i: σ} {p: MvPolynomial σ k} {I: Set (MvPolynomial σ k)} {β : ℕ}

/- The algebraic set of a set of polynomials S ⊆ k[x₁, ... xₙ] is the set
of elements x ∈ kⁿ such that x is a root of all the polynomials in S -/
def IsAlgebraic (S: Set (MvPolynomial σ k)) : Set (σ → k) := {x : (σ → k) | ∀ f ∈ S, (MvPolynomial.eval x) f = 0}

/- Here the underlying set is a set of elements in kⁿ -/
structure AlgebraicSet (k: Type*) [CommSemiring k] (σ : Type*) where
  (carrier: Set (σ → k))
  (is_algebraic: ∃ S : Set (MvPolynomial σ k), carrier = IsAlgebraic S)

--def CoordRing (X: AlgebraicSet k σ) := (σ → k) / X

/- A variety is an irreducible algebraic set -/
def IsVariety (X: AlgebraicSet k σ) (U₁ U₂: AlgebraicSet k σ) := X.carrier ≠ ∅ ∧ X.carrier ≠ U₁.carrier ∧ X.carrier ≠ U₂.carrier ∧ X.carrier ≠ U₁.carrier ∪ U₂.carrier

/- Every variety V has a dimension which is the transcendence degree of function
field k(V) over k; here I am just defining it as a number ≥ 0 -/
structure Variety (X: AlgebraicSet k σ) where
  (carrier: Set (σ → k))
  (is_variety: ∀ U₁ U₂ : AlgebraicSet k σ, IsVariety X U₁ U₂)
  (dimension : ℕ)

-- cannot find anything related to transcendence degree in Mathlib, but dim could also just be defined as some non-neg number in lean since the definition is not too important for proving this question
--def Dim (X: AlgSet) := Algebra.Transcendental (Mv_Polynomial X k) k

variable (A : AlgebraicSet k σ)

/- If Y is a subvariety of X, then the codimension of Y in X is dim X - dim Y -/
def Codim (X: Variety A) (Y: Variety A) (Y_sub_X: Y.carrier ⊆ X.carrier) := X.dimension - Y.dimension


/- Next two theorems are to help prove the main problem -/

/-
Theorem 2.5.3:
If Y is a proper subvariety of X ⊆ Am then dim Y < dim X.
Proof:
Let n = dim X.
Then any n+1 of the coordinate functions x1, . . . , xm are algebraically dependent as elements of k(X), and also as elements of k(Y ).
Therefore dimY ≤dimX.
Assume that dim Y = dim X .
We will derive the contradiction Y = X by showing that I(Y) ⊆ I(X).
Since dimY = n there are coordinate functions xi1,...,xin whose images are algebraically independent in k(Y). Then xi1 , . . . , xin must be algebraically independent in k(X).
Let u ∈ Γ(X) be non- zero.
Then u depends algebraically on xi1 , . . . , xin , i.e. there is a polynomial a ∈ k[t1,...,tn+1] such that
a(u,xi1,...,xin)=ak(xi1,...,xin)uk +···+a1(xi1,...,xin)u+a0(xi1,...,xin)=0 on X.
Since Γ(X) is a domain we may assume a is irreducible and a0(xi1 , . . . , xin ) is non-zero on X.
Then a(u,xi1,...,xin)=0 on Y since Y ⊆ X so if u=0 on Y then a0(xi1,...,xin) = 0 on Y, a contradiction since xi1,...,xin are algebraically independent in k(Y ).
Since u ≠ 0 on X implies u  ≠ 0 on Y we have that I(Y ) ⊆ I(X).
-/

theorem ProperSubVarietyDim (X Y: Variety A) (properSub: Y.carrier ⊂ X.carrier) : Y.dimension < X.dimension := by
  sorry

/-
Let f ∈ k[x1, . . . , xn] be a non-constant irreducible polynomial. Then V(f) ⊆ 𝔸ⁿ has codimension 1.

Proof:
Let X = V(f).
Suppose that xₙ appears in the expression of f.
Then x1, . . . , xn-1 are algebraically independent in k(X).
Indeed, if they are not then there is a polynomial g involving only the variables x1,...,xn−1 that is zero on X.
Then g ∈ I(X) = ⟨f⟩, so f | g and xn appears in the expression for g, a contradiction.
Therefore dim X ≥ n − 1, and Theorem 2.5.3 implies that dim X = n − 1, so codim X = 1.
-/

theorem IrredCodim1 (f: MvPolynomial σ k) (Vf: Variety A) (kn: Variety A) (h: Vf.carrier ⊆ kn.carrier): kn.dimension - Vf.dimension = 1 := by
  sorry

/-
Let I ⊂ k[x1, . . . , xn] be an ideal that can be generated by r elements.
Show that every irreducible component of V (I) has dimension ≥ n − r.
-/

-- need to revise the arguments to this
theorem IrredDim (I: Set (MvPolynomial r k)) (W: Variety A) {r: ℕ} {n: ℕ} : W.dimension ≥ n - r := by
  sorry
  /- induction on r using d:
  if d = 1:
  then I = ⟨a₁⟩ ⊆ k[x₁, ..., xₙ]
  so V(I) = V(a₁) = V(f₁) ∩ ... ∩ V(fₘ) where fᵢ is an irreducible factor of a₁
  since k is a UFD, each V(fᵢ) is irreducible and has a codimension of 1 in 𝔸ⁿ
  hence dim V(fᵢ) ≥ n - 1 (from equation codimₖ(V(fᵢ)) = dim k - dim V(fᵢ)


  if d = r - 1
  Let V(I) = V(a1, ... ar-1) = ∪ Wᵢ where Wᵢ is irreducible and dim Wᵢ ≥ n - r + 1
  X = V(a1, ... ar) = V(a1, ... ar-1) ∩ V(ar) = ∪ Wᵢ ∩ V(aᵣ)
  X is the union of irreducible decompositions of ∪ Wᵢ ∩ V(aᵣ)
  We show every irreducible component W of Wᵢ ∩ V(aᵣ) has dim W ≥ n - r

  If polynomial aᵣ = 0:
  then all of 𝔸ⁿ is its algebraic set, so Wᵢ ∩ V(aᵣ) = Wᵢ
  Since Wᵢ is irreducible, W = Wᵢ
  so dim W ≥ n - r + 1 ≥ n - r

  If aᵣ ≠ 0 in coordinate ring of Wᵢ:
  Every irreducible component of Wᵢ ∩ V(aᵣ) has codimension 1 in Wᵢ
  So dim W = dim (Wᵢ) - 1 ≥ n - r + 1 - 1 = n - r

  -/
